# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Hey-Common
version:      0.01
version_from: lib/Hey/Common.pm
installdirs:  site
requires:
    Digest::SHA1:                  0
    Net::SMTP:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
